services:
  db:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: []

  php:
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_ENV: prod
    volumes:
      - ./drupal:/var/www/html
      - drupal-files:/var/www/html/web/sites/default/files

  nginx:
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./drupal:/var/www/html:ro
      - drupal-files:/var/www/html/web/sites/default/files:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
volumes:
  drupal-files:
