services:
  db:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: []

  php:
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_ENV: prod
    volumes:
      - ./drupal:/var/www/html
      - drupal-files:/var/www/html/web/sites/default/files

  nginx:
    image: forcewatch-nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile.prod
    restart: unless-stopped
    ports:
      - "80:80"
    volumes: []
    depends_on:
      - php
      - react
  react:
    image: forcewatch-react-prod
    build:
      context: .
      dockerfile: docker/react/Dockerfile.prod
    restart: unless-stopped
    ports:
      - "4173:4173"
    environment:
      VITE_API_BASE: /api
volumes:
  drupal-files:
